import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Content from "@/components/Content";
import SecondaryBar from "@/components/SecondaryBar";
import { useEffect, useState } from "react";
import Header from "@/components/Header";

export default function Home() {
  const [windowWidth, setWindowWitdh] = useState<number>(0);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setWindowWitdh(window.innerWidth);
      const handleResize = () => setWindowWitdh(window.innerWidth);
      window.addEventListener("resize", handleResize);
      return () => {
        window.removeEventListener("resize", handleResize);
      };
    }
  }, []);
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {windowWidth < 768 && <Header />}
        <div className="md:flex justify-between min-h-screen">
          {<Sidebar windowWidth={windowWidth} />}
          <Content />
          {windowWidth > 768 && <SecondaryBar />}
        </div>
      </main>
    </>
  );
}
